import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ZukuGameBridge,ZukuGameBridgeError} from '../dist/game-bridge.js';
class Frame extends EventTarget {
 sent=[];parent={postMessage:(message,origin)=>this.sent.push({message,origin})};
 emit(data,{origin='https://www.zuzunza.com',source=this.parent}={}){const event=new Event('message');Object.assign(event,{data,origin,source});this.dispatchEvent(event);}
}
const session='fixture-session-nonce';
function create(t,options={}){const window=new Frame();const bridge=new ZukuGameBridge({window,session,parentOrigin:'https://www.zuzunza.com',...options});t.after(()=>bridge.close());return {window,bridge};}
const reply=(window,index=0,data={ok:true})=>{const message=window.sent[index].message;window.emit({...message,success:true,data});};
test('bridge sends exact existing host protocol and explicit origin with no account credential API',async t=>{const {window,bridge}=create(t);const promise=bridge.request('context');assert.deepEqual(Object.keys(window.sent[0].message),['channel','version','session','id','action','payload']);assert.equal(window.sent[0].origin,'https://www.zuzunza.com');assert.equal(window.sent[0].message.channel,'zuku-game-cloud');reply(window);assert.deepEqual(await promise,{ok:true});assert.equal(bridge.token,undefined);assert.equal(bridge.fetch,undefined);});
test('foreign source/origin/session/version/channel cannot resolve host request',async t=>{const {window,bridge}=create(t);let resolved=false;const p=bridge.request('context').then(v=>{resolved=true;return v;});const msg={...window.sent[0].message,success:true,data:{forged:true}};window.emit(msg,{source:{}});window.emit(msg,{origin:'https://evil.example'});window.emit({...msg,session:'wrong'});window.emit({...msg,version:2});window.emit({...msg,channel:'other'});await Promise.resolve();assert.equal(resolved,false);reply(window,0,{real:true});assert.deepEqual(await p,{real:true});});
test('two bridge instances use unique request IDs and ignore cross-instance replies',async t=>{const window=new Frame();const a=new ZukuGameBridge({window,session,parentOrigin:'https://www.zuzunza.com'}),b=new ZukuGameBridge({window,session,parentOrigin:'https://www.zuzunza.com'});t.after(()=>{a.close();b.close();});const pa=a.request('context'),pb=b.request('context');assert.notEqual(window.sent[0].message.id,window.sent[1].message.id);reply(window,1,{who:'b'});reply(window,0,{who:'a'});assert.deepEqual(await pa,{who:'a'});assert.deepEqual(await pb,{who:'b'});});
test('account change rejects old pending write unknown and old replies cannot resolve new request',async t=>{const {window,bridge}=create(t);const old=bridge.request('save',{slot:'a',data:{score:5}});window.emit({channel:'zuku-game-cloud-auth',version:1,session});await assert.rejects(old,e=>e.code==='ACCOUNT_CHANGED'&&e.outcome==='unknown');const fresh=bridge.request('context');let done=false;fresh.then(()=>{done=true;});reply(window,0,{old:true});await Promise.resolve();assert.equal(done,false);reply(window,1,{new:true});assert.deepEqual(await fresh,{new:true});});
test('capability limits reject unknown actions, credentials, account/project impersonation and huge values',async t=>{const {window,bridge}=create(t);for(const payload of [{authorization:'fixture'}, {data:{access_token:'fixture'}},{userId:'foreign'}, {projectId:'foreign'},{data:'a'.repeat(16385)}])await assert.rejects(bridge.request('save',payload),e=>e.code==='INVALID_PAYLOAD');await assert.rejects(bridge.request('run-shell'),e=>e.code==='ACTION_UNSUPPORTED');assert.equal(window.sent.length,0);});
test('bridge concurrency bounded to three and completed requests free slots',async t=>{const {window,bridge}=create(t);const promises=[bridge.request('context'),bridge.request('load'),bridge.request('scores-list')];await assert.rejects(bridge.request('context'),e=>e.code==='BRIDGE_BUSY');for(let i=0;i<3;i++)reply(window,i);await Promise.all(promises);const next=bridge.request('context');reply(window,3);await next;});
test('bridge caller cancellation and timeout distinguish possible write outcome',async t=>{const {window,bridge}=create(t,{timeoutMs:15});await assert.rejects(bridge.request('save'),e=>e.code==='REQUEST_TIMEOUT'&&e.outcome==='unknown');const abort=new AbortController();const pending=bridge.request('context',{}, {signal:abort.signal});abort.abort();await assert.rejects(pending,e=>e.code==='REQUEST_CANCELLED'&&e.outcome==='failed');assert.equal(window.sent.length,2);});
test('malformed or credential-bearing host response is rejected without secret propagation',async t=>{const {window,bridge}=create(t);const pending=bridge.request('context');reply(window,0,{access_token:'fixture-private'});await assert.rejects(pending,e=>e.code==='INVALID_RESPONSE'&&!String(e).includes('fixture-private'));const next=bridge.request('context');window.emit({...window.sent[1].message,success:false,error:{code:'UNAUTHORIZED',message:'fixture-private'}});await assert.rejects(next,e=>e.code==='UNAUTHORIZED'&&!String(e).includes('fixture-private'));});
test('closed bridge unsubscribes and refuses requests',async t=>{const {window,bridge}=create(t);const pending=bridge.request('context');bridge.close();await assert.rejects(pending,e=>e.code==='BRIDGE_CLOSED');await assert.rejects(bridge.request('context'),e=>e.code==='BRIDGE_CLOSED');window.emit({channel:'zuku-game-cloud-auth',version:1,session});});
test('bridge requires a real selected host, valid nonce and exact origin',()=>{for(const parentOrigin of ['*','https://www.zuzunza.com/path','http://example.test','https://fixture:secret@example.test'])assert.throws(()=>new ZukuGameBridge({window:new Frame(),session,parentOrigin}),ZukuGameBridgeError);assert.throws(()=>new ZukuGameBridge({window:new Frame(),session:'tiny',parentOrigin:'https://www.zuzunza.com'}),e=>e.code==='INVALID_SESSION');const win=new Frame();win.parent=win;assert.throws(()=>new ZukuGameBridge({window:win,session,parentOrigin:'https://www.zuzunza.com'}),e=>e.code==='HOST_REQUIRED');});
