import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {ZukuClient,ZukuApiError,validateSchema} from '../dist/index.js';
const envelope=data=>({success:true,data,meta:{version:'v1'}});
const content={id:'cnt_fixture',category:'jump',type:'html5',title:'Game',creator:{id:'usr_1',handle:'tester',display_name:'Tester',avatar_url:'',is_verified:false},stats:{like_count:0,comment_count:0,view_count:0,share_count:0,bookmark_count:0},created_at:'2026-10-04T00:00:00Z',updated_at:'2026-10-04T00:00:00Z'};
const pagination={page:1,per_page:1,total:1,total_pages:1,has_next:false,has_prev:false,next_cursor:null,prev_cursor:null};
const feed=envelope({feeds:[content],pagination,sort:'new'});
const json=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json',...headers}});
const error=code=>e=>e instanceof ZukuApiError&&e.code===code;
async function http(t,handler){const server=createServer(handler);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{server.closeAllConnections();server.close();});return `http://127.0.0.1:${server.address().port}/api/v1`;}
test('existing helpers use real plural content and auth endpoints/envelopes',async()=>{
 const seen=[];const client=new ZukuClient({fetch:async(url,init)=>{seen.push(new URL(url).pathname);return json(url.endsWith('/auth/me')?envelope({user:{id:'usr_1',email:'fixture@example.test',handle:'tester',created_at:'2026-10-04T00:00:00Z',profile_completion_status:'complete'}}):url.includes('/contents/')?envelope({content}):feed);}});
 assert.equal((await client.getContentList('opaque+/=')).data.feeds[0].id,'cnt_fixture');await client.getContent('cnt_fixture');await client.getCurrentUser();assert.deepEqual(seen,['/api/v1/feeds','/api/v1/contents/cnt_fixture','/api/v1/auth/me']);
});
test('real HTTP encodes query, merges headers, uses omit/error and validates success',async t=>{
 let seen;const baseUrl=await http(t,(req,res)=>{seen={url:req.url,headers:req.headers};res.writeHead(200,{'Content-Type':'application/json','X-Request-ID':'fixture-123'});res.end(JSON.stringify(feed));});
 const captured=[];const client=new ZukuClient({baseUrl,token:'fixture-account-access',apiKey:'fixture-api-key',headers:{'X-Default':'a','X-Override':'before'},fetch:async(url,init)=>{captured.push(init);return fetch(url,init);}});
 const result=await client.operations.getFeeds({query:{cursor:'a+/=?&',per_page:1}},{headers:{'X-Override':'after'}});
 assert.equal(result.success,true);assert.equal(new URL(seen.url,baseUrl).searchParams.get('cursor'),'a+/=?&');assert.equal(seen.headers['x-default'],'a');assert.equal(seen.headers['x-override'],'after');assert.equal(seen.headers.authorization,'Bearer fixture-account-access');assert.equal(seen.headers['x-api-key'],'fixture-api-key');assert.equal(captured[0].redirect,'error');assert.equal(captured[0].credentials,'omit');assert.equal(captured[0].cache,'no-store');
});
test('actual PATCH content method and logical key are transmitted once',async t=>{
 let seen,count=0;const baseUrl=await http(t,async(req,res)=>{count++;let body='';for await(const chunk of req)body+=chunk;seen={method:req.method,body:JSON.parse(body),key:req.headers['idempotency-key']};res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(envelope({content})));});
 const client=new ZukuClient({baseUrl});await client.operations.updateContent({path:{id:'cnt_fixture'},body:{title:'Updated'}},{idempotencyKey:'deployment-fixture-01'});
 assert.deepEqual(seen,{method:'PATCH',body:{title:'Updated'},key:'deployment-fixture-01'});assert.equal(count,1);
});
test('logical deployment key supports explicit recovery lookup',async()=>{
 let seen;const client=new ZukuClient({fetch:async url=>{seen=url;return json(envelope({deployment:{idempotency_key:'logical:key01',content_id:'cnt_fixture',status:'published',reserved_at:null,completed_at:'2026-10-04T00:00:00Z',package_sha256:'a'.repeat(64),size_bytes:4}}));}});
 const result=await client.operations.getGameDeployment({path:{key:'logical:key01'}});assert.equal(result.data.deployment.status,'published');assert.ok(seen.endsWith('/oauth/games/deployments/logical%3Akey01'));
});
test('multipart boundary is runtime-owned and file bytes reach actual HTTP',async t=>{
 let body,ct;const baseUrl=await http(t,async(req,res)=>{ct=req.headers['content-type'];body=Buffer.concat(await Array.fromAsync(req));res.writeHead(201,{'Content-Type':'application/json'});res.end(JSON.stringify(envelope({upload:{url:'/uploads/fixture.zip',kind:'archive',mime:'application/zip',size:4,sha256:'a'.repeat(64),original_name:'blob'}})));});
 const client=new ZukuClient({baseUrl,headers:{'Content-Type':'wrong/boundary'}});await client.operations.uploadMedia({body:{file:new Blob(['PK\u0003\u0004'])}});
 assert.match(ct,/^multipart\/form-data; boundary=/);assert.ok(body.includes(Buffer.from('name="file"')));assert.ok(body.includes(Buffer.from('PK\x03\x04')));
});
test('binary game package is a Uint8Array without JSON conversion',async t=>{
 const baseUrl=await http(t,(_,res)=>{res.writeHead(200,{'Content-Type':'application/zip'});res.end(Buffer.from([80,75,3,4]));});assert.deepEqual([...await new ZukuClient({baseUrl}).operations.getGamePackage({path:{id:'cnt_fixture'}})],[80,75,3,4]);
});
test('binary route rejects an HTML login response',async()=>{const client=new ZukuClient({fetch:async()=>new Response('<html>login</html>',{headers:{'Content-Type':'text/html'}})});await assert.rejects(client.operations.getGamePackage({path:{id:'c'}}),error('UNEXPECTED_CONTENT_TYPE'));});
test('204 deletion never attempts JSON parsing',async t=>{
 const baseUrl=await http(t,(_,res)=>{res.writeHead(204);res.end();});assert.equal(await new ZukuClient({baseUrl}).operations.deleteComment({path:{id:'comment-fixture'}}),undefined);
});
test('structured HTTP errors retain safe code/request ID/rate delay without body',async()=>{
 const client=new ZukuClient({readRetries:0,fetch:async()=>json({success:false,error:{code:'RATE_LIMITED',message:'fixture-account-access'},meta:{version:'v1',request_id:'fixture-req'}},429,{'Retry-After':'2'})});
 await assert.rejects(client.getCurrentUser(),e=>{assert.equal(e.kind,'http');assert.equal(e.requestId,'fixture-req');assert.equal(e.retryAfterMs,2000);assert.equal(e.code,'RATE_LIMITED');assert.ok(!String(e).includes('fixture-account-access'));return true;});
});
test('non-JSON HTTP error normalized and sensitive HTML discarded',async()=>{const client=new ZukuClient({readRetries:0,fetch:async()=>new Response('<b>fixture-private</b>',{status:502})});await assert.rejects(client.getCurrentUser(),e=>e.status===502&&e.code==='HTTP_ERROR'&&!String(e).includes('fixture-private'));});
test('missing envelope or wrong content payload is an explicit response contract error',async()=>{for(const payload of [{data:{}},envelope({content:{id:'cnt_bad'}})]){const c=new ZukuClient({fetch:async()=>json(payload)});await assert.rejects(c.getContent('cnt_bad'),error('INVALID_RESPONSE'));}});
test('malformed JSON success is explicit',async()=>{const client=new ZukuClient({fetch:async()=>new Response('{invalid',{headers:{'Content-Type':'application/json'}})});await assert.rejects(client.getCurrentUser(),error('INVALID_JSON_RESPONSE'));});
test('success with undeclared status is explicit',async()=>{const client=new ZukuClient({fetch:async()=>json(envelope({user:{}}),201)});await assert.rejects(client.getCurrentUser(),error('UNEXPECTED_STATUS'));});
test('response limits apply to Content-Length and streamed body',async()=>{for(const headers of [{},{'Content-Length':'999'}]){const c=new ZukuClient({maxResponseBytes:8,fetch:async()=>new Response('123456789', {headers})});await assert.rejects(c.getCurrentUser(),error('RESPONSE_TOO_LARGE'));}});
test('timeout enforced even when injected fetch ignores AbortSignal',async()=>{const client=new ZukuClient({timeoutMs:15,fetch:()=>new Promise(()=>{})});await assert.rejects(client.getCurrentUser(),error('REQUEST_TIMEOUT'));});
test('timeout includes token retrieval and prevents network submission',async()=>{let calls=0;const client=new ZukuClient({timeoutMs:15,getToken:()=>new Promise(()=>{}),fetch:async()=>{calls++;return json(feed);}});await assert.rejects(client.getContentList(),e=>e.code==='REQUEST_TIMEOUT'&&e.outcome==='failed');assert.equal(calls,0);});
test('caller cancellation aborts an active HTTP request and marks mutation unknown',async t=>{
 const baseUrl=await http(t,()=>{});const abort=new AbortController();const client=new ZukuClient({baseUrl});const promise=client.operations.likeContent({path:{id:'cnt_fixture'}},{signal:abort.signal});setTimeout(()=>abort.abort(),20);await assert.rejects(promise,e=>e.code==='REQUEST_CANCELLED'&&e.outcome==='unknown');
});
test('already cancelled request performs no network calls',async()=>{let n=0;const abort=new AbortController();abort.abort();const c=new ZukuClient({fetch:async()=>{n++;return json(feed);}});await assert.rejects(c.getContentList(undefined,{signal:abort.signal}),error('REQUEST_CANCELLED'));assert.equal(n,0);});
test('safe reads retry bounded transient HTTP errors; non-transient errors do not',async()=>{let n=0;const c=new ZukuClient({retryDelayMs:0,fetch:async()=>++n===1?json({},503):json(feed)});await c.getContentList();assert.equal(n,2);n=0;const bad=new ZukuClient({fetch:async()=>{n++;return json({},401);}});await assert.rejects(bad.getContentList());assert.equal(n,1);});
test('safe read network retry does not expose injected error',async()=>{let n=0;const c=new ZukuClient({retryDelayMs:0,fetch:async()=>{if(++n===1)throw new Error('fixture-secret');return json(feed);}});await c.getContentList();assert.equal(n,2);});
test('toggle/write never retries on network/429/503 even with readRetries 3',async()=>{for(const status of [0,429,503]){let n=0;const c=new ZukuClient({readRetries:3,fetch:async()=>{n++;if(!status)throw new Error('fixture-private');return json({},status);}});await assert.rejects(c.operations.likeContent({path:{id:'cnt_fixture'}}),e=>!String(e).includes('fixture-private')&&(status===429?e.outcome==='failed':e.outcome==='unknown'));assert.equal(n,1);}});
test('real HTTP redirect never forwards Bearer to redirected destination',async t=>{let destination=0;const baseUrl=await http(t,(req,res)=>{if(req.url==='/credential-target'){destination++;res.end('{}');}else{res.writeHead(307,{Location:'/credential-target'});res.end();}});const c=new ZukuClient({baseUrl,token:'fixture-account-access',readRetries:0});await assert.rejects(c.getCurrentUser());assert.equal(destination,0);});
test('injected fetch redirect response also rejected',async()=>{const c=new ZukuClient({fetch:async()=>new Response(null,{status:308,headers:{Location:'https://example.test'}})});await assert.rejects(c.getCurrentUser(),error('REDIRECT_REFUSED'));});
test('native OAuth omits browser cookies even when browser integration enabled',async()=>{let seen;const c=new ZukuClient({credentials:'same-origin',fetch:async(_,init)=>{seen=init;return json(envelope({limit:3,window_seconds:21600,used:0,pending:0,remaining:3,reset_at:null,retry_after:0}));}});await c.operations.getDeployQuota();assert.equal(seen.credentials,'omit');});
test('invalid input fails before fetch without leaking field values',async()=>{let n=0;const c=new ZukuClient({fetch:async()=>{n++;return json(feed);}});await assert.rejects(c.operations.getFeeds({query:{per_page:1000,unapproved:'fixture-secret'}}),e=>e.code==='INVALID_REQUEST'&&!JSON.stringify(e).includes('fixture-secret'));assert.equal(n,0);});
test('invalid logical key is rejected without network',async()=>{let n=0;const c=new ZukuClient({fetch:async()=>{n++;return json(feed);}});await assert.rejects(c.operations.likeContent({path:{id:'c'}},{idempotencyKey:'bad key'}),error('INVALID_IDEMPOTENCY_KEY'));assert.equal(n,0);});
test('forbidden credential routing headers fail closed',async()=>{for(const h of ['Cookie','Host','Proxy-Authorization']){const c=new ZukuClient({headers:{[h]:'fixture'},fetch:async()=>json(feed)});await assert.rejects(c.getContentList(),error('FORBIDDEN_HEADER'));}});
test('auth retrieval errors normalized without secret stack/cause',async()=>{const c=new ZukuClient({getToken:()=>{throw new Error('fixture-private-token');}});await assert.rejects(c.getContentList(),e=>e.code==='AUTH_CONFIGURATION_ERROR'&&!String(e).includes('fixture-private-token')&&e.cause===undefined);});
test('custom base rejects userinfo, remote HTTP and query without raw URL disclosure',()=>{for(const baseUrl of ['https://fixture-secret@example.test','http://example.test','https://example.test?token=fixture-secret','not a URL'])assert.throws(()=>new ZukuClient({baseUrl}),e=>e.code==='INVALID_BASE_URL'&&!String(e).includes('fixture-secret'));});
test('unsupported legacy routes fail explicitly while supported aliases use unified paths',async()=>{let seen=[];const c=new ZukuClient({fetch:async url=>{seen.push(url);return json(url.includes('/contents/')?envelope({content}):envelope({feeds:[],pagination:{per_page:20,has_next:false,next_cursor:null},sort:'new'}));}});for(const id of ['unlikeContent','unfollowCreator','recordSwipeWatch','createGameReview','getGameLeaderboard','getCreatorAnalytics','getReport','getAdminDashboard','getAdminContents','moderateContent','interactHypeContent','oauthRedirect'])await assert.rejects(c.operations[id]({}),error('CONTRACT_UNSUPPORTED'));await c.operations.getHypeContent({path:{id:'cnt_fixture'}});await c.operations.getSwipeFeedAlt();assert.equal(seen.length,2);assert.ok(seen[0].includes('/contents/'));assert.equal(new URL(seen[1]).searchParams.get('mode'),'stream');await assert.rejects(c.getUser('usr_fixture'),error('CONTRACT_UNSUPPORTED'));});
test('validator handles refs/union/ranges, missing required and bounded hostile keys without values',()=>{assert.equal(validateSchema({oneOf:[{type:'string'},{type:'number'}]},true)[0].rule,'oneOf');assert.equal(validateSchema({type:'integer'},1.2)[0].rule,'type');assert.equal(validateSchema({type:'object',required:['id'],properties:{id:{type:'string'}},additionalProperties:false},{'fixture-secret':'secret'})[1].path,'$.*');});
test('unsafe JSON values are rejected rather than silently coerced',async()=>{const c=new ZukuClient({fetch:async()=>json(envelope({}))});for(const value of [NaN,undefined,new Date(),1n])await assert.rejects(c.operations.saveCloudSlot({body:{projectId:'p',data:value}}),e=>['INVALID_JSON','INVALID_REQUEST'].includes(e.code));});
export {envelope,content,pagination};
test('path dot segments cannot escape the configured API base',async()=>{let calls=0;const c=new ZukuClient({fetch:async()=>{calls++;return json(feed);}});for(const id of ['.','..'])await assert.rejects(c.getContent(id),error('INVALID_PATH'));assert.equal(calls,0);});
test('unsafe request accessors do not execute during validation',async()=>{let executed=0;const body={projectId:'p'};Object.defineProperty(body,'data',{get(){executed++;return {};},enumerable:true});await assert.rejects(new ZukuClient().operations.saveCloudSlot({body}),error('INVALID_REQUEST'));assert.equal(executed,0);});
test('invalid header bytes normalize without leaking values',async()=>{const c=new ZukuClient({headers:{'X-Test':'fixture-private\nvalue'}});await assert.rejects(c.getContentList(),e=>e.code==='INVALID_HEADERS'&&!String(e).includes('fixture-private'));});
test('runtime config rejects include credentials even when TypeScript is bypassed',()=>{assert.throws(()=>new ZukuClient({credentials:'include'}),error('INVALID_CONFIG'));assert.throws(()=>new ZukuClient({fetch:42}),error('INVALID_CONFIG'));});
